envelope-zero/frontend

.github/ISSUE_TEMPLATE/bug_report.md
Adds a bug report template to enable better bug reports.
=> docs: bug report template

src/components/Layout.tsx
=> fix: navgiation -> navigation

.dockerignore, .github/workflows/build.yml, .pre-commit-config.yaml, Dockerfile, package.json
Adds a Dockerfile and pushes the OCI image on tags and the `main` branch.
=> feat: add Dockerfile and OCI image build

Dockerfile, README.md, src/lib/api/budgets.ts
- make css work
- make api requests work
=> Fix docker build

src/components/Layout.tsx
=> feat: change order of items in nav 

src/components/BudgetSwitch.tsx, src/lib/budget-helper.ts, src/translations/en.json
=> feat: clearer fallback name for untitled budgets

src/components/BudgetForm.tsx
=> feat: submit form on pressing enter

src/components/BudgetSwitch.tsx, src/translations/en.json
=> feat: display instructional text if no budgets exist yet

public/index.html, public/manifest.json
=> feat: replace default meta attributes with actual app info

src/App.tsx, src/components/AccountForm.tsx, src/components/BudgetForm.tsx, src/components/BudgetSwitch.tsx, src/components/Dashboard.tsx, src/components/OwnAccountsList.tsx, src/lib/api/accounts.ts, src/lib/api/base.ts, src/lib/api/budgets.ts, src/types.d.ts
Support [v0.16.0](https://github.com/envelope-zero/backend/releases/tag/v0.16.0) & [v0.17.0](https://github.com/envelope-zero/backend/releases/tag/v0.17.0) of the backend
=> feat: support new API structure

src/components/TransactionForm.tsx, src/types.d.ts
=> fix default values for transaction

public/index.html
Cleans the comments from the index.html template.
=> refactor: clean up template

CONTRIBUTING.md, Makefile
Adds some more documentation for other developers.
=> docs: development server instructions

src/components/TransactionsList.tsx
=> fix: sort transactions from newest to oldest

src/lib/api/transactions.ts
=> rely on backend sorting of transactions 

src/App.tsx
=> delete budgetId cookie if budget wasn't found

src/lib/cookie.ts
=> fix: samesite attribute on cookie

src/components/Autocomplete.tsx, src/components/TransactionForm.tsx, src/translations/en.json
=> allow setting an empty envelope

src/App.tsx, src/components/TransactionForm.tsx, src/components/TransactionsList.tsx, src/lib/api/base.ts, src/types.d.ts
- Fix list after creating & editing transactions (closes #258)
- Correctly apply filters to transactions list
=> Fix transactions list

.github/CODEOWNERS
Adds code owners for automatic pull request review requests.
=> test: add codeowners file to automatically request reviews

renovate.json
This automates minor and patch version upgrades for:
- Dockerfile
- docker-compose-.*.yml
It will effectively auto-upgrade:
- npm minor and patch versions
- EZ backend minor and patch version updates
=> chore(renovate): automatically upgrade minor versions in Dockerfile and docker-compose.*.y?ml

cypress/e2e/transactions.cy.ts, cypress/support/commands.ts, cypress/support/index.d.ts, cypress/support/setup.ts, src/components/AccountForm.tsx, src/components/EnvelopeForm.tsx, src/components/LatestTransactions.tsx, src/components/LoadingSpinner.tsx, src/components/TransactionsList.tsx, src/lib/transaction-helper.ts, src/translations/en.json, src/types.d.ts
Transaction testing, plus a few fixes & improvements
closes #337
=> test: transactions

src/components/EnvelopesList.tsx, src/translations/en.json
=> feat: empty state for envelope list

cypress/e2e/categories-envelopes.cy.ts, cypress/e2e/transactions.cy.ts, src/components/CategoryEnvelopes.tsx, src/components/EnvelopesList.tsx, src/translations/en.json
=> test: add category and envelope tests

src/components/AccountForm.tsx, src/components/BudgetForm.tsx, src/components/CategoryForm.tsx, src/components/EnvelopeForm.tsx, src/components/TransactionForm.tsx
=> feat: automatically focus first input

cypress/e2e/transactions.cy.ts, src/components/Autocomplete.tsx, src/components/TransactionForm.tsx, src/translations/en.json
=> feat: clearer selection of empty envelope

src/index.tsx
This reverts commit 044d40103287cfc1db6f8d5c493c168ec4aea2f5 and resolves #17.
=> test: revert "disable strict mode for now"

cypress/e2e/budgets.cy.ts, src/App.tsx, src/components/Layout.tsx
this prevents the app from rendering a blank page whenever an error occurs while loading the budget
=> fix: let Layout display potential errors

cypress/e2e/budgets.cy.ts, src/lib/api/base.ts, src/lib/api/budgets.ts, src/lib/trim-whitespace.ts
=> feat: trim whitespace from all fields

renovate.json
With this PR, renovate PRs that pin dependencies will be automatically merged.
=> chore(deps): automatically merge pin PRs

src/components/TransactionForm.tsx
=> feat: set current date by default

src/components/BudgetSwitch.tsx
=> fix: make link only as wide as necessary

cypress/e2e/transactions.cy.ts, src/components/EnvelopeMonth.tsx, src/components/TransactionForm.tsx
=> fix: allow decimals for number inputs

src/App.scss
=> style: hide arrows on number inputs

cypress/e2e/categories-envelopes.cy.ts, src/lib/fetch-helper.js
=> fix: throw error properly

cypress/e2e/dashboard.cy.ts, cypress/support/setup.ts, src/components/EnvelopeMonth.tsx
This links all Envelopes in the Dashboard to the transactions list, filtered by the envelope.
With this change, it gets easier to find relevant transactions.
=> feat: link envelope to its transactions

.github/workflows/workflow.yml, package-lock.json, package.json
This reverts commit 40b16bceed7fcd36b029b0ac1ebf1bbf488ea39e.
=> Revert "test: run cypress 5 times in CI to detect flakey tests"

cypress/e2e/transactions.cy.ts, src/components/TransactionForm.tsx
=> fix: clear form inputs when creating a new transaction

src/components/TransactionForm.tsx
=> fix: don't clear state on invalid input 

cypress/e2e/budgets.cy.ts, src/components/AccountForm.tsx, src/components/BudgetForm.tsx, src/components/CategoryForm.tsx, src/components/EnvelopeForm.tsx, src/lib/submit-on-meta-enter.ts
=> feat: submit form when pressing CTRL/CMD + Enter in textarea

src/App.scss, src/components/CategoryMonth.tsx, src/components/Dashboard.tsx, src/components/EnvelopeMonth.tsx, src/translations/en.json
=> feat: add spent column for wide screens

.github/CODEOWNERS
This removes me as code owner for the end to end tests.
=> test: update codeowners

cypress/e2e/budgets.cy.ts, cypress/fixtures/ynab4-budget.json, cypress/fixtures/ynab4-budget.yfull, src/App.tsx, src/components/BudgetForm.tsx, src/components/BudgetImport.tsx, src/components/BudgetSwitch.tsx, src/components/FlyoutMenu.tsx, src/components/FormField.tsx, src/translations/en.json
=> feat: import YNAB 4 budgets

src/components/BudgetSwitch.tsx
since they don't really add any valuable information
Closes #616
=> feat: remove balances from budget list

cypress/e2e/accounts.cy.ts, src/components/AccountForm.tsx, src/components/InputCurrency.tsx, src/components/TransactionForm.tsx, src/translations/en.json, src/types.d.ts
=> feat: record initial balance for accounts

cypress/e2e/transactions.cy.ts, src/components/TransactionForm.tsx, src/translations/en.json, src/types.d.ts
=> feat: suggest recent envelope(s) when selecting an account for a transaction

cypress/e2e/dashboard.cy.ts, src/components/AllocationInputs.tsx, src/components/EnvelopeMonth.tsx, src/components/Modal.tsx, src/translations/en.json
=> feat: allow editing an allocation by a relative amount

package-lock.json, package.json, src/components/AllocationInputs.tsx
=> fix: avoid floating point errors in relative allocation calculation

src/components/GroupedTransactions.tsx, src/components/LatestTransactions.tsx, src/components/TransactionsList.tsx, src/types.d.ts
=> feat: group latest transactions by date

.github/workflows/workflow.yml, cypress/e2e/accounts.cy.ts, docker-compose-dev.yml, docker-compose-test.yml, src/App.scss, src/components/AccountForm.tsx, src/components/ArchiveButton.tsx, src/components/ExternalAccountsList.tsx, src/components/Notification.tsx, src/components/OwnAccountsList.tsx, src/translations/en.json, src/types.d.ts
See #533 
This leads to accounts created before [backend v1.5.0](https://github.com/envelope-zero/backend/releases/tag/v1.5.0) being invisible, which will be fixed in backend v2.1.2
=> Feat: archive accounts

src/components/ArchiveButton.tsx, src/components/CategoryEnvelopes.tsx, src/components/CategoryForm.tsx, src/components/EnvelopeForm.tsx, src/components/EnvelopesList.tsx, src/translations/en.json, src/types.d.ts
=> feat: archive envelopes & categories

cypress/e2e/transactions.cy.ts, src/components/ArchiveButton.tsx, src/components/Autocomplete.tsx, src/types.d.ts
=> feat: hide archived resources from autocomplete dropdown

src/components/CategoryMonth.tsx, src/components/Dashboard.tsx
(This isn't working yet because of https://github.com/envelope-zero/backend/issues/552. Once the backend issue is fixed, this should start working as intended.)
=> fix: hide hidden categories & envelopes in dashboard

cypress/e2e/transactions.cy.ts, src/components/SearchBar.tsx, src/components/TransactionsList.tsx, src/translations/en.json, src/types.d.ts
=> feat: search transaction list

cypress/e2e/transactions.cy.ts, src/App.scss, src/components/Autocomplete.tsx, src/components/TransactionFilters.tsx, src/components/TransactionForm.tsx, src/components/TransactionsList.tsx, src/translations/en.json, src/types.d.ts
=> Filter transactions

src/App.scss, src/components/Dashboard.tsx
=> fix: don't break layout on long budget names

src/components/TransactionForm.tsx
=> fix: make repeat button clickable over the whole width

cypress/e2e/dashboard.cy.ts, src/components/CategoryMonth.tsx
=> fix: don't count archived envelopes

cypress/e2e/transactions.cy.ts, src/components/TransactionForm.tsx
=> fix: allow transaction amount with leading zeros

src/components/EnvelopeMonth.tsx
=> feat: link from dashboard to envelope

cypress/e2e/transactions.cy.ts, src/components/TransactionForm.tsx
=> Improve available from

.github/workflows/workflow.yml, CONTRIBUTING.md, README.md, package.json
This updates the test config and documentation to work correctly with month pickers.
=> test: test and documentation updates

renovate.json
We need a token for lookups in the GitHub npm registry.
=> chore: set token for GitHub npm registry lookups

cypress/e2e/dashboard.cy.ts, cypress/e2e/transactions.cy.ts, package-lock.json, package.json, vite.config.ts
This package is not used.
Closes #1128.
=> chore: remove vite-plugin-svgr

src/components/TransactionImport/Result.tsx
=> fix: clear error when navigating to different transaction in import

cypress/e2e/transaction-import.cy.ts, cypress/fixtures/comdirect.csv, src/components/TransactionForm.tsx, src/components/TransactionImport/Result.tsx, src/lib/account-helper.ts, src/lib/dates.ts, src/lib/transaction-helper.ts
=> fix: show 'Available From' field in import

cypress/e2e/transactions.cy.ts, src/components/TransactionForm.tsx
=> fix: do not suggest envelopes from the transaction source

cypress/e2e/transaction-import.cy.ts, src/components/TransactionImport/Result.tsx
=> fix: wrap transaction import form in <form> tag

cypress/e2e/categories-envelopes.cy.ts, src/components/EnvelopeForm.tsx
=> fix: prioritize new category over previous value

.github/workflows/cleanup-images.yml
=> ci: delete images - set correct ignore

src/App.scss
=> fix: keep header absolute on desktop

cypress/e2e/transaction-import.cy.ts, src/components/ImportBanner.tsx, src/components/Layout.tsx, src/components/TransactionImport/Form.tsx, src/components/TransactionImport/Result.tsx, src/components/TransactionImport/index.tsx, src/translations/en.json
=> feat: persist transaction import

cypress/e2e/transaction-import.cy.ts, src/components/TransactionImport/Result.tsx, src/translations/en.json
=> feat: improve wording when dismissing transactions in import

src/components/InfiniteScroll.tsx, src/components/TransactionsList.tsx, src/lib/api/base.ts
=> feat: load transaction list in batches to enable infinite scroll

.pre-commit-config.yaml, renovate.json
- **chore: migrate GitHub NPM registry access token for Hosted renovate**
- **chore: migrate deprecated pre-commit config**
=> chore: migrate config and renovate token

src/components/TransactionImport/Form.tsx
=> fix: make transaction import account selection dropdown fully visible

src/App.scss, src/components/Dashboard.tsx
=> feat: make dashboard headers sticky

cypress/e2e/accounts.cy.ts, src/components/ExternalAccountsList.tsx, src/types.d.ts
=> feat: add search bar to external account list

src/App.scss
Looking at https://github.com/envelope-zero/frontend/pull/1909#issuecomment-2705928603 again, I decided to explicitly style our placeholders.
=> style: lighter placeholder text

src/components/ExternalAccountsList.tsx
=> fix: truncate account name

cypress/e2e/dashboard.cy.ts, src/components/CategoryMonth.tsx, src/components/Dashboard.tsx, src/components/EnvelopeMonth.tsx
=> fix: show allocation error within modal

package-lock.json, package.json
to fix styles until we can upgrade Tailwind to v4
=> chore: downgrade flowbite

src/components/MonthPicker.tsx
closes https://github.com/envelope-zero/frontend/issues/1436
=> fix: submit month picker with enter

src/App.scss, src/components/TransactionImport/Result.tsx, src/translations/en.json
fixes https://github.com/envelope-zero/frontend/issues/1013
=> fix: disable button while submitting
