envelope-zero/frontend

.github/workflows/renovate-config-validator.yml

This should fix the failing runs on main when the file has not been changed.

fix: only trigger renovate config validation on actual changes

---

Dockerfile
default.conf

This uses nginx `try_files` to serve the requested file and fall back to `/index.html` if it does not exist.

fix: use try_files to enable "virtual paths"

---

default.conf

This sets aggressive caching (1 year) for resources where the URL is hashed with the content, 7 days for images and no-cache for `index.html`.

feat: set caching directives

---

.github/workflows/renovate-config-validator.yml

Tags do not evaluate path filters, therefore this gets a bit more complicated.

test: run renovate config validator only on changes to config or the test workflow

---

README.md
src/components/Autocomplete.tsx
src/lib/api/accounts.ts
src/lib/api/budgets.ts
src/lib/api/transactions.ts
src/types.d.ts

Adds support for UUIDs as IDs.
BREAKING CHANGE: This version is only compatible with v0.22.0+ of
the backend.

feat!: IDs are now UUIDs

---

renovate.json

Set the semantic scope back to "chore" as we use conventional commit style, not angular.

chore: set semantic commit scope to default

---

src/components/TransactionsList.tsx

This was an idea to highlight transactions that have no note, but it is not intuitive and therefore removed.

feat: no transactions need to be shown in italics

---

.github/workflows/cypress.yml

Electron has problems with flaky tests. Since we do not run the frontend in Electron anywhere, use Chrome.

test: use chrome to fix flaky Electron tests

---

cypress/e2e/budgets.cy.ts
cypress/support/commands.ts
cypress/support/index.d.ts

This introduces a 'wait for the next page to be loaded after save'
function for our tests.

test: fix flaky contains after save

---

README.md

Small typo fix.
Thanks @fhreichert for the report!

docs: fix typo in releases link

---

.github/workflows/workflow.yml
cypress/support/commands.ts

cypress now deletes all resources before starting a new test.
This depends on #311.

test: clean all resources before every test

---

.github/workflows/workflow.yml
CONTRIBUTING.md
cypress/e2e/accounts.cy.ts
cypress/support/commands.ts
cypress/support/setup.ts
docker-compose-dev.yml
docker-compose-test.yml
package-lock.json
package.json
src/lib/api/base.ts
src/setupProxy.js

This
* configures a development proxy
* removes the env variable `REACT_APP_API_ENDPOINT` in favor of using the proxy
* adds helper functions for testing
* adds tests for accounts
Note: The proxy setup is in `setupProxy.js` as create-react-app does not support proxy setup with typescript (yet).

test: add account tests

---

cypress/e2e/api.cy.ts
src/App.tsx

This introduces a new route for /api that does nothing
With this route, requests for /api get send to the server.
This enables users to open the API in their browser without
annoying workarounds.
Fixes #108.

feat: send API requests to backend

---

cypress/e2e/budgets.cy.ts
src/App.tsx

fix: show budget switch if selected budget can't be loaded

---

.github/workflows/workflow.yml
package-lock.json
package.json

With this, all tests run 5 times in the CI. The command exits with an error if any tests fail or with success when none fails.
This is one possible way of repeating tests, others are described in https://www.cypress.io/blog/2020/12/03/retry-rerun-repeat/#repeat.
This increases cypress test run time a lot, but will detect flakes much better than we currently do (i.e. by accident).
@malfynnction what do you think?

test: run cypress 5 times in CI to detect flakey tests

---

cypress/e2e/budgets.cy.ts
cypress/support/e2e.ts

This fixes some flakyness by always visiting a page to trigger loading.
In another test case, it fixes flakyness by using clickAndWait instead
of click to save resources.

test: fix flaky tests

---

src/lib/fetch-helper.js

If the HTTP response is not ok and the body is not json, we now throw
the text of the body as error message instead of an object (which would
lead to rendering an empty page).
Resolves #247.

fix: throw non-json error responses correctly

---

cypress/e2e/dashboard.cy.ts
cypress/e2e/transactions.cy.ts

This fixes multiple issues where cypress would check
for content before loading was finished.

test: add wait commands for loading

---

.github/workflows/workflow.yml
docker-compose-dev.yml
docker-compose-test.yml
src/components/Dashboard.tsx
src/types.d.ts

With the release of the backend in v1.13.0, including https://github.com/envelope-zero/backend/pull/474, we can add the spent sum for the month.

feat: add spent for whole month

---

.vscode/launch.json

Adds a launch config for Firefox.
With this, you can launch the VSCode debugger, which launches Firefox and enables breakpoints, variable inspection etc.

feat: add VSCode launch config to debug with Firefox

---

src/components/CategoryMonth.tsx
src/components/Dashboard.tsx
src/components/EnvelopeMonth.tsx
src/components/LatestTransactions.tsx
src/components/TransactionsList.tsx
src/lib/format.ts

With this change, the columns “Spent” and “Balance” for an individual envelope in the dashboard stay empty if the number is zero.
Categories will still show a zero amount when collapsed.

feat: do not show 0 amounts for individual envelopes in spent and balance columns

---

src/components/CategoryMonth.tsx
src/components/Dashboard.tsx
src/types.d.ts

This makes use of the new fields introduced in
https://github.com/envelope-zero/backend/pull/500.
With this change, no more sums are calculated locally.

refactor: use new fields on backend for dashboard

---

cypress/e2e/dashboard.cy.ts
src/components/CategoryMonth.tsx
src/components/Dashboard.tsx
src/components/EnvelopeMonth.tsx

We currently show a sign for positive envelope balances. This is not needed.

feat: do not show sign for positive balances

---

.github/workflows/workflow.yml
README.md
docker-compose-dev.yml
docker-compose-test.yml
src/components/CategoryMonth.tsx
src/components/Dashboard.tsx
src/components/EnvelopeMonth.tsx

This flips the colors on the spent column to incorporate the changes with backend 2.0.0

feat: flip colors for spent amount with backend 2.0.0

---

src/components/FormField.tsx

To avoid fun browser errors like this one:
This fixes #637

fix: set step='any' on number inputs by default

---

src/components/TransactionFilters.tsx

so that both amount (min & max) and date (from & until) filters are displayed next to each other on all devices

fix: rearrange filters 

---

cypress/e2e/dashboard.cy.ts
src/App.scss
src/components/Dashboard.tsx
src/components/QuickAllocationForm.tsx
src/translations/en.json
src/types.d.ts

feat: quick allocation

---

renovate.json

This updates the renovate config to use some more recommended templates.
It also includes configuration with a regexManager that will apply node versioning to the OCI image used in the `Dockerfile` to keep it in sync with the node version from `package.json`.
With this configuration, it will always use the **Active LTS** version.

chore(deps): use all renovate replacement and workaround presets

---

src/components/TransactionsList.tsx

It makes more sense closer to the search bar and the list of filters than next to the "create transaction" button. Before vs. after:

feat: move filter button to a more intuitive place

---

README.md
src/translations/en.json

THis updates the link pointing to the import documentation to a short link that we can update when moving documentation.
Details about the short link service are in https://envelope-zero.org/docs/project-infrastructure/#short-link-service

chore: update documentation and instructions link

---

.github/workflows/workflow.yml

This pushes all images, enabling debugging.

ci: always push built image to enable debugging

---

cypress/e2e/dashboard.cy.ts
src/components/EnvelopeMonth.tsx

This adds the `fromDate` and `untilDate` to the transaction list links generated on the dashboard.
With this, when clicking on an amount on the dashboard, only transactions for the month the user
is currently viewing will be shown in the transaction list.

feat: filter transactions by month when clicking a link on the dashboard

---

src/components/TransactionForm.tsx

The backend enforces the availability date to be no earlier than the month of the
transaction from version v3.1.4 on with https://github.com/envelope-zero/backend/pull/789.
The frontend does not set this correctly yet when duplicating transactions.
This PR fixes that behavior.

fix: set availability date to the current date on transaction duplication

---

.pre-commit-config.yaml
renovate.json

This will keep all used node versions aligned.

chore: use node versioning for node Docker image

---

renovate.json

These upgrades are handled with a customManager, therefore the Dockerfile
manager is conflicting.

chore: disable renovate dockerfile manager for node

---

.pre-commit-config.yaml
src/components/TransactionForm.tsx
src/translations/en.json

This adds information about why the "Available From" field is a date picker on
browsers that do not support `input type="month"`.
On Firefox:
On Chromium:

fix: reduce user confusion by adding information about the date/month picker

---

.github/workflows/cleanup-images.yml

This adds a CI job to clean up old image versions that are not semver.

ci: clean up old images

---

.github/workflows/workflow.yml
cypress/e2e/dashboard.cy.ts

With https://github.com/envelope-zero/frontend/pull/1092 a test with `cy.only` was added. This runs only this test and skips all other dashboard tests.

test: run all dashboard tests

---

cypress/e2e/dashboard.cy.ts
src/components/AllocationInputs.tsx
src/components/FormField.tsx

When using the "Set amount" field it is usually intended to override the value. By selecting the text onFocus the user can start typing right away.

feature: select text of input field when setting an allocation

---

.github/workflows/workflow.yml

This updates the workflow to only run on 
- PRs
- pushes to the `main` branch, to keep caches up-to-date
- pushes to tags, to release

ci: only run on main and tags

---

.github/workflows/workflow.yml
CONTRIBUTING.md
cypress.config.ts

This adds configuration for cypress cloud.
- Tests will continue to log to the GitHub actions logs
- Tests are running in parallel (currently 6 runners with a matrix job, configured as recommended by Cypress Cloud). This results in much faster run times than before.
- The Envelope Zero project in Cypress Cloud is public: https://cloud.cypress.io/projects/uc2vus

ci: use cypress cloud

---

.github/workflows/workflow.yml

This fixes the CI not releasing new image versions on tags.

ci: fix missing push in ci

---

.github/workflows/workflow.yml

This adds more platforms to build for, so that the image can run natively
on macOS and Windows machines, too.

ci: add more platforms

---

README.md
docker-compose-dev.yml
docker-compose-production.yml
docker-compose-test.yml
src/components/OwnAccountsList.tsx
src/components/TransactionForm.tsx
src/lib/api/base.ts
src/lib/format.ts
src/types.d.ts

With this, the frontend uses API v4. API v4 removes computed endpoints
from resource collection endpoints and exposes these at new endpoints.
This requires a few more API calls from frontend, but greatly improves
performance since we only request data when it's needed.
BREAKING CHANGE: With this change, the frontend requires backend version v4.2.2.

feat!: use API v4

---

.github/workflows/workflow.yml
.npmrc
CONTRIBUTING.md
Dockerfile
cypress/e2e/dashboard.cy.ts
cypress/e2e/transaction-import.cy.ts
cypress/e2e/transactions.cy.ts
docker-compose-dev.yml
docker-compose-production.yml
docker-compose-test.yml
package-lock.json
package.json

This will make maintenance and contributions easier.
Since envelope-zero/you-need-a-parser now publishes exclusively to npmjs, we need to update this anyways.
Resolves #1559.

chore(deps): install ynap-parsers from npmjs

---

src/components/TransactionForm.tsx
src/types.d.ts

With this, income is considered in the recent envelopes.
In the recent envelopes, income is represented as a recent envelope with the ID `null`.
Therefore, we need to check for this specific case and not use it as suggestion when it is the first
in the list of recent envelopes.
We also need to remove it from the recent envelopes list.

fix: consider income in recent envelopes

---

.github/workflows/workflow.yml
renovate.json

This changes the GitHub actions workflow so that images for each architecture are built separately and then merged together.

ci: build images in one matrix job per architecture

---

.github/matrix.json
.github/workflows/workflow.yml

With this change, image builds for arm64 are only run for tags, speeding up PR testing significantly (the arm64 build takes > 5 minutes).
The image build now also does not wait for pre-commit and cypress to finish anymore, since releases are only made when both are successful anyways.

ci: only build arm image on release, do not block image build with other jobs

---

.github/workflows/workflow.yml

Enables merge group in the workflow to make it easier to merge multiple PRs.

ci: enable merge groups

---

.github/workflows/workflow.yml

With these checks added, we can use the merge queue together with cypress.
Unfortunately, cypress publishes the status checks as "cypress: default-group (merge)" for a PR and "cypress: default-group" in the merge queue. 
Therefore we need to have a successful job for the respective other name in our workflow.

ci: fix cypress check names

---

renovate.json

With this, the renovate config should be correct again.

chore: update renovate config to remove encrypted config

---

cypress/e2e/transaction-import.cy.ts
cypress/e2e/transactions.cy.ts
src/components/TransactionForm.tsx
src/components/TransactionImport/Result.tsx
src/lib/dates.ts

With this, the default AvailableFrom date is set to the first of the month following the transaction, not the month of the transaction.
This makes more sense logically since it enforces funds to only be allocated after they have been received by default.
The value can still be explicitly set if that is required.

feat!: set default available from to next month

---

renovate.json

We need to rebase only when a PR is conflicted, since the merge queue enforces tests with up-to-date config.

chore(renovate): only rebase when needed

---

Dockerfile

Fixes the deprecated `ENV key value` format, using `ENV key=value` instead.

chore: fix Dockerfile deprecations

---

.github/workflows/workflow.yml
docker-compose-dev.yml
docker-compose-production.yml
docker-compose-test.yml
src/components/TransactionImport/Result.tsx

This PR sets the availableFrom month to the next month by default for imports.
I missed this in 52df7a4b50606c1c19994377715771f8a6a44c6a, so with this commit created transactions and imports behave the same again.
This also fixes a bug where the import form correctly displayed the next month as availableFrom, but the transaction was imported incorrectly.

fix: set availableFrom to next month on import

---

renovate.json

Since updates might sometimes be blocked by other updates that are rate-limited, we're disabling the rate limiting.

ci: disable renovate limiting

---

.pre-commit-config.yaml
index.html

The pre-commit prettier hook does not work anymore, so we run prettier as a local hook.

ci: run current prettier version

---

renovate.json

See https://docs.renovatebot.com/configuration-options/#rangestrategy for details:
> replace = Replace the range with a newer one if the new version falls outside it, and update nothing otherwise

chore(deps): replace instead of pin npm version

---

src/lib/dates.ts

This fixes a bug where the next month was not correctly calculated during the month on which daylight savings time goes into effect.
As far as I'm aware, that month is March everywhere.
This only affected the "Available From" setting for income transactions for frontend versions 4.0.0 and newer, and only if these transactions were created between midnight and 01:00 your local time.
If you are using the frontend in version 4.0.0 or newer and have created transactions between midnight and 01:00 in March 2025, please verify that the Available From date is correct for those transactions.

fix: available from date and daylight savings time

---

cypress/e2e/transaction-import.cy.ts
cypress/fixtures/import-untitled-account.csv
src/components/TransactionImport/Result.tsx

This fixes a bug where when the source or destination account could not be parsed on import and was not matched by any match rule, it was shown as "Untitled Account".
Resolves https://github.com/envelope-zero/frontend/issues/1763

fix: no longer show "Untitled Account" on import when account is not known
